{{- define "chc-lib.hpa" }}
{{- $hpa := .Values.hpa -}}
{{- if $hpa.create }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" (dict "values" (list $hpa.labels .Values.commonLabels) "context" .) | fromYaml }}
  labels: {{ include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list $hpa.annotations .Values.commonAnnotations) "context" .) | fromYaml }}
  {{- if $annotations }}
  annotations: {{ include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  minReplicas: {{ $hpa.minReplicas }}
  maxReplicas: {{ $hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    name: {{ include "common.names.fullname" . }}
    {{- if eq .Values.controller.kind "Deployment" }}
    kind: Deployment
    {{- else if eq .Values.controller.kind "StatefulSet" }}
    kind: StatefulSet
    {{- end }}

  metrics:
    {{- if $hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
