{{- define "chc-lib.podmonitor" }}
{{- $podmonitor := .Values.prometheusOperator.podMonitor -}}
{{- if and .Values.prometheusOperator.enabled $podmonitor.create }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ $podmonitor.namespaceOverride | default .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" (dict "values" (list $podmonitor.labels .Values.commonLabels) "context" .) | fromYaml }}
  labels: {{ include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list $podmonitor.annotations .Values.commonAnnotations) "context" .) | fromYaml }}
  {{- if $annotations }}
  annotations: {{ include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}

  {{ if $podmonitor.podMetricsEndpoints -}}
  podMetricsEndpoints:
  {{- range $key, $value := $podmonitor.podMetricsEndpoints }}
    - port: {{ $key }}
      {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 6 }}
  {{- end }}
  {{- else }}
  podMetricsEndpoints: {}
  {{- end }}
{{- end }}
{{- end }}
