{{- define "chc-lib.serviceaccount" }}
{{- $serviceaccount := .Values.serviceAccount -}}
{{- if $serviceaccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chc-lib.helpers.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" (dict "values" (list $serviceaccount.labels .Values.commonLabels) "context" .) | fromYaml }}
  labels: {{ include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 4 }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list $serviceaccount.annotations .Values.commonAnnotations) "context" .) | fromYaml }}
  {{- if $annotations }}
  annotations: {{ include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $serviceaccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
